name: ci
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3
              with:
                  version: 9.4.0

            - uses: actions/setup-node@v4
              with:
                  node-version: "23"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile

            - name: Run Prettier
              run: pnpm run prettier --check .

            - name: Create test env file
              run: |
                  echo "TEST_DATABASE_CLIENT=sqlite" > packages/core/.env.test
                  echo "NODE_ENV=test" >> packages/core/.env.test

            # - name: Run tests
            # run: cd packages/core && pnpm test // YOLO FOR NOW

            - name: Build packages
              run: pnpm run build
